### ISSUE TITLE
Palemoon compatibility

### ISSUE THREAD

**Issue by ask2018** [warren-bank/fork-moz-modifyheaders-response#2]
Hi. Since version 29.2.0 Palemoon is not allowing Firefox legacy extension.
https://www.ghacks.net/2021/04/28/pale-moon-29-2-0-does-not-support-legacy-firefox-extensions-anymore-that-are-not-ported/
In most cases it is just about adding Palemoon signature to the install.rdf file. Could you make your extension compatible please?

**Comment by warren-bank** [comment]
[here](https://github.com/warren-bank/fork-moz-modifyheaders-response/releases/tag/response%2Fv0.7.1.1%2Fv1.06) you are

though I'm no-longer using Firefox (or any of its forks), nor actively supporting any of the Firefox addons that I had written back in the day.. as you said, this only required a very minor configuration update; I tested it in Pale Moon 29.2.0 (portable for Win64), and it still works properly.
