### ISSUE TITLE
Modify header at specific website only

### ISSUE THREAD

**Issue by ask2018** [warren-bank/fork-moz-modifyheaders-response#3]
It is possible to add function to modify the headers for specific website only? Like I can add for example some header only for example - https://www.somedomain.com/something/somepage and I can make a list of such rules in the extension?

**Comment by warren-bank** [comment]
although:
* I'm not actively supporting this legacy addon
* this addon is a mirror image of the original upstream addon, which only supports modifying request headers
  - as such, it was never my intention to change the UI or set of capabilities

that said:
* [moz-rewrite](https://github.com/warren-bank/moz-rewrite) is an older addon that I wrote
  - it is much more capable, though less user-friendly
  - it comes in 3x versions
    * [this version](https://github.com/warren-bank/moz-rewrite/releases/tag/json%2Fv1.05) is the simplest to use
      - it reads configuration from JSON data files
      - I just released an update so it will continue to work in Pale Moon 29.2.0+
      - I just tested this release in PM 29.2.0 and it still works properly

- - - -

super quick summary of how to test `moz-rewrite/json/master` in Pale Moon portable:
1. unzip Pale Moon portable to a directory:
   - `C:\PortableApps\Pale Moon\29.2.0`
2. create directory:
   - `C:\PortableApps\Pale Moon\29.2.0\User\Palemoon\Profiles\Default\moz-rewrite-json`
3. create files:
   - `C:\PortableApps\Pale Moon\29.2.0\User\Palemoon\Profiles\Default\moz-rewrite-json\requests.json`
   - `C:\PortableApps\Pale Moon\29.2.0\User\Palemoon\Profiles\Default\moz-rewrite-json\responses.json`
4. update content of `responses.json` file:
   ```json
     [
       {
         "url" : "^.*$",
         "headers" : {
           "Access-Control-Allow-Origin" : "*",
           "Content-Disposition"         : null,
           "Content-Security-Policy"     : null,
           "X-Content-Security-Policy"   : null
         }
       }
     ]
   ```
5. open options for addon on `about:addons`
   - HTTP Requests (outbound):
     * disable the checkbox (until needed)
     * enter path:
       - `{ProfD}/moz-rewrite-json/requests.json`
   - HTTP Responses (inbound):
     * enable the checkbox
     * enter path:
       - `{ProfD}/moz-rewrite-json/responses.json`
   - click: OK
6. test the above rule by:
   - opening any random webpage, such as: `about:blank`
   - open devtools to use the javascript console
   - run the following line of javascript to confirm that the XHR bypasses CORS restrictions:
     ```javascript
       fetch('https://www.google.com/').then(response => response.text()).then(console.log)
     ```

**Comment by ask2018** [comment]
Great,  thank you. That works exactly as I needed and json is enough user friendly for me. And also thanks for updating addons for Pale Moon compatibility.

**Comment by warren-bank** [comment]
You're welcome. And I appreciate that you informed me about the new Pale Moon policy toward legacy addons; adding explicit support for PM was quick and easy.. well worthwhile.
